helmDefaults:
  createNamespace: true
  wait: true

repositories:
  - name: stable-old
    url: https://charts.helm.sh/stable

  - name: jetstack
    url: https://charts.jetstack.io

  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: stable-old/nginx-ingress
    version: 1.41.3

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.1.0
    values:
      - installCRDs: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args: ["apply", "-f", "../cert-manager/cert-manager-production-issuer.yaml"]

  - name: harbor
    needs:
      - cert-manager/cert-manager
    namespace: harbor
    chart: harbor/harbor
    version: 1.5.2
    values:
      - ../harbor/values.yaml
