apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod
commonAnnotations:
  oncallPager: 123-456-7890
namePrefix: prod-
namespace: hipster-shop-prod

bases:
  - ../../base
